spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/toongather
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: scott
    password: tiger

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hgk.2024.multi@gmail.com
    password: wbunuzwdsvuchgmx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

server:
  port: 8099
  servlet:
    session:
      timeout: 1800
    encoding:
      charset: UTF-8
      enabled: true

logging:
  level:
    org:
      springframework:
        jdbc: TRACE
        transaction: TRACE
    com:
      .zaxxer: TRACE
    sql: TRACE

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

naver:
  clova:
    chatbot:
      url: "https://47rv9xlkxz.apigw.ntruss.com/custom/v1/15453/1d0c6942878611a5035ae2c26a030d4ad5cf83dd80bae0be2465b367c583b806"
      secret: "b2hFQ2VzeVpqU0txdHp0dWFDd1J4Q2x1R3pHVXRmSEc="

